---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: false
  chef_license: accept-no-persist
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: amazonlinux-2
  - name: centos-6
  - name: centos-7
  - name: centos-8
  - name: debian-9
  - name: debian-10
  - name: fedora-latest
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: apt_repos
    includes:
      - debian-9
      - debian-10
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::apt_repos]

  - name: cron
    run_list:
      - recipe[test::cron]

  - name: cron_d
    run_list:
      - recipe[test::cron_d]

  - name: directory
    run_list:
      - recipe[test::directory]

  - name: groups
    run_list:
      - recipe[test::groups]

  - name: users
    run_list:
      - recipe[test::users]

  - name: yum_repos
    includes:
      - amazonlinux
      - centos-6
      - centos-7
    run_list:
      - recipe[test::yum_repos]

  - name: iptables_d
    includes:
      - centos-6
      - centos-7
    run_list:
    - recipe[test::iptables_d]

  - name: sudoers_d
    run_list:
    - recipe[test::sudoers_d]

  - name: init_d
    includes:
      - amazonlinux
      - centos-6
    run_list:
    - recipe[test::init_d]
