AllCops:
  NewCops: enable

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"
